server:
    #指定服务端口号
    port: 8888
eureka:
    client:
        #是否需要将自己注册到注册中心，因为该工程自己就是服务注册中心，所以无需注册。如果是多个服务注册中心集群模式，则另当别论
        register-with-eureka: false
        #是否向注册中心定时更新自己状态
        fetch-registry: false
        serviceUrl:
            #注册中心的位置,默认为8761
            defaultZone: http://localhost:8888/eureka/

    server:
#        关闭自我保护模式
        enable-self-preservation: false